#define PERIPHS_IO_MUX_MTDO_U 0
#define PERIPHS_IO_MUX_MTDI_U 0
#define PERIPHS_IO_MUX_U0RXD_U 0
#define PERIPHS_IO_MUX_U0TXD_U 0
#define PERIPHS_IO_MUX_GPIO4_U 0
#define PERIPHS_IO_MUX_GPIO5_U 0

#define FUNC_GPIO15 0
#define FUNC_GPIO12 0
#define FUNC_GPIO3 0
#define FUNC_GPIO4 0
#define FUNC_GPIO5 0
#define FUNC_U0TXD 0


#define BIT_RATE_115200 0

#define STATIONAP_MODE 0
#define STATION_MODE 1

#define AUTH_WPA_WPA2_PSK 0
